#build new version of pages
#this means:
#0 setup dot
#1 preprocess dotfile using sed to replace node and link type definitions
#2 preprocess dotfile using sed to create two dotfiles, one with show links and one with edit links
#3 build two svgs,one for show and one for edit, using dot
#4 run markdown on all md files to make html versions
#5 push to repository
#5 in future put all of this into _site which will be page actually served
name: BUILD_DOC
on:
  push:
  #workflow_dispatch: #for now, manual, later (after debugging and initial website setup) revert to automatic
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: step 0 setup graphiz & markdown
        run: |
          set -x
          set -v
          echo before # should use a sed script file, will change after debugging
          sudo apt-get install graphviz
          sudo apt-get install markdown
          echo after
      - name: step 1 macro-process dotfile
        run: |
          set -x
          set -v
          echo before # should use a sed script file, will change after some more debugging
          #sed -E "s/(WEBSERVICE)/[shape=rectangle][color=green]/" editme.dot > dotinprocess.dot
          #sed -E "s/(TOOL)/[shape=rectangle][color=blue]/" dotinprocess.dot > dotinprocess1.dot
          #sed -E "s/(DATA)/[color=red]/" dotinprocess1.dot > dotinprocess2.dot
          sed -E -f replacings.sed editme.dot > dotinprocess2.dot
          echo after
      - name: step 2 make two dotfiles
        run: |
          set -x
          set -v
          echo before
          sed -E "s/%%([a-zA-Z0-9_\/ -]+)%%/[URL=\"https:\/\/github.com\/tilnow\/tilnow.github.io\/edit\/master\/\1.md\"]/" dotinprocess2.dot > editlinkdot.dot
          sed -E "s/%%([a-zA-Z0-9_\/ -]+)%%/[URL=\"https:\/\/tilnow.github.io\/\1.html\"]/" dotinprocess2.dot > showlinkdot.dot
          echo after
      - name: step 3 build two svgs
        run: |
          set -x
          set -v
          echo before
          cat editlinkdot.dot
          dot -Tsvg editlinkdot.dot -o editable.svg
          cat showlinkdot.dot
          dot -Tsvg showlinkdot.dot -o displayable.svg
          echo after
      - name: step 4 process markdowns and cleanup
        run: |
          set -x
          set -v
          echo before
          cm md
          for file in *.md; do 
          echo "processing $file"
          markdown "$file" > "../${file%.md}.html"; 
          done
          cd ..
          rm dotinprocess2.dot
          rm editlinkdot.dot
          rm showlinkdot.dot
          echo after
      - name: step 5 update file with link file
        run: |
            echo before
            touch -a index.html #so that it will work if we ran from branch 
            #echo ___ > .gitignore - not clear what to ignore at this point
            git config user.name tilnow
            git config user.email tilnowah@gmail.com
            git add .
            number=$(date "+%s")
            git commit -m "updated dotfile $number"
            git push 
            echo after 

